// Lista de frases
    const phrases = [
      "They are scaling back the marketing budget",
      "I need to finish this report by tomorrow",
      "The conference starts at nine o'clock sharp",
      "She is considering a career change",
      "We should discuss this in more detail",
      "The project requires additional funding",
      "They implemented the new system successfully",
      "Customer satisfaction is our top priority",
      "The meeting has been postponed until next week",
      "We need to improve our communication strategy",
      "The company is expanding into new markets",
      "This approach will increase our efficiency",
      "They are analyzing the market trends",
      "We should reconsider our pricing strategy",
      "The team achieved outstanding results",
      "Innovation drives our business forward",
      "We are committed to sustainable practices",
      "The deadline has been extended by two days",
      "They are developing a new product line",
      "We must address these issues immediately",
      "The presentation was well received",
      "They are evaluating different options",
      "We need to optimize our processes",
      "The results exceeded our expectations",
      "Collaboration is key to our success",
    ];
    